### ISSUE TITLE
'tooltip' function not work in guild bank

### ISSUE THREAD

**Issue by Lucifer050a** [arkayenro/arkinventory#1299]
Rules use 'tooltip' function are work well in bag and character's bank, but can't work in guild bank.
~~Is it a bug  or 'feature'(limited by wow's api)?~~
suggest the check function(ArkInventoryRules.System.boolean_tooltip) set Toolip Object by hyperlink when item is in guild bank.

**Comment by Ninjakitten** [comment]
I've hit this issue as well. It's making it pretty tricky to create certain rules!

**Comment by arkayenro** [comment]
tooltips are painful.  its fine for the bag as you always have access, but the bank, you have no access if its not open.

the tooltip function is written to use the bag/slot id if you have access, otherwise it uses the hyperlink (which contains no soulbound, or some other, data) so you get just the base item.

**Comment by Ninjakitten** [comment]
Thank you for your reply! I can see the issue with that if trying to check things in banks you're not currently at, definitely. What if it _is_ open, though? I was trying to make a rule that would put collectibles in my guild bank that I don't know yet (pets, mounts, toys, etc) in their own little section, and it seems like using tooltip to look for 'Collected' and 'Already known' is the only way to really do that. It works in the bag, which fits what you said, but not in the bank, even if I'm standing at the open bank right then. Is there another way to do it with arkinventory, or would it need some other sort of code to check the list of pets/mounts/toys an account 'knows' and then compare to see if the item is in that list already? (A couple other things would have been easier with tooltip working there as well, but I was able to find workarounds for those.)

**Comment by arkayenro** [comment]
pets/mounts/toys shouldnt matter for tooltip purposes, theres only the base item.

the item count logic knows how to check how many you have but for rule purposes there is nothing that will tell you if you have learnt them or not.  i'd have to build a new rule function for that.

**Comment by Lucifer050a** [comment]
i use tooltip func to check fragments of material that have text 'use', so whatever use hyper or slot works fine for me, and most of guild bank items is meterials and consumables. now problem is when i open guild bank offline works fine but open it online.
i add this code into `function ArkInventory.TooltipSetItem( tooltip, bag_id, slot_id )`
```
elseif bag_id > 1000 then
    return ArkInventory.TooltipSetGuildBankItem(tooltip, bag_id - 1000, slot_id)
```
i'm not sure is it a good way but it's solve my problem.

**Comment by arkayenro** [comment]
i have no idea how that would solve your problem as every call to that function has already converted from AI values to blizzard values, none would be over 1000 so it should never run your code.  not to mention that you cant just take 1000 off the AI bag value if it was somehow passed in there.

**Comment by arkayenro** [comment]
ah, i see whats going on

**Comment by arkayenro** [comment]
try the latest alpha and see if its working properly for you now.

**Comment by arkayenro** [comment]
fixed in 3.09.23/24

**Comment by Lucifer050a** [comment]
the tooltip function still not work correct.
 i add printout in `ArkInventoryRules.System.boolean_tooltip` function, it's just print 0.
```
if  ArkInventoryRules.Object.info.id == XXXX then
	print(ArkInventory.TooltipGetNumLines( ArkInventoryRules.Tooltip ))
	for i = 1, ArkInventory.TooltipGetNumLines( ArkInventoryRules.Tooltip ) do
		print(_G[string.format( "%s%s%s", ArkInventoryRules.Tooltip:GetName( ), "TextLeft", i )]:GetText())
	end
end
```
if i change `TooltipSetGuildBankItem` to `TooltipSetHyperlink` will work fine.
i dont know why item info is accessed but `SetGuildBankItem` not work.

**Comment by arkayenro** [comment]
vault tooltips are returning data for me.  and a tooltip( "restore" ) rule is working in there

what is the rule you you are having an issue with?

change it to this, it should dump out the vault tooltip data.

```
		ArkInventory.TooltipSetItem( ArkInventoryRules.Tooltip, ArkInventoryRules.Object.loc_id, ArkInventoryRules.Object.bag_id, ArkInventoryRules.Object.slot_id, ArkInventoryRules.Object.h, ArkInventoryRules.Object )
		
		if loc_id == ArkInventory.Const.Location.Vault and ArkInventory.Global.Mode.Vault then
			ArkInventory.TooltipDump( ArkInventoryRules.Tooltip )
		end
```

**Comment by Lucifer050a** [comment]
my rule is `type(7) and subtype(8) and tooltip('use')`. the dump message is `lines = 0`.

i found first open tab after login/reload the rule not work, but after eidt the rule (add space behind 'and') it's work fine and dump message show `lines = 3`.

**Comment by arkayenro** [comment]
thats sort of normal that the game can take a while to generate a proper tooltip.

i'll add a cache reset if it has to rescan which should help it to cope with that
