### ISSUE TITLE
Lua error when mousing over reputation items

### ISSUE THREAD

**Issue by Gwalkmaur** [arkayenro/arkinventory#1363]
Receive the following error anytime I mouse over any kind of reputation item, whether in bag or in missions.

```
ArkInventory\ArkInventory-30936.lua:12471:`` ...ns\ArkInventory\ArkInventoryCollectionReputation.lua:200: attempt to index local 'object' (a nil value)
[string "=[C]"]: ?
[string "@ArkInventory\ArkInventory-30936.lua"]:12471: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "...ns\ArkInventory\ArkInventoryCollectionReputation.lua:200: attempt to index local 'object' (a nil value)"
```

Using 3.09.36

**Comment by arkayenro** [comment]
somehow youre getting an invalid reputation id.  i'll add in a check to make it it returns something.

**Comment by arkayenro** [comment]
should be fixed in 3.09.37

**Comment by Gwalkmaur** [comment]
The fix for this has opened a new issue:
`ArkInventory\ArkInventory-30937.lua:12469: ...ns\ArkInventory\ArkInventoryCollectionReputation.lua:201: attempt to index local 'object' (a nil value)
[string "=[C]"]: ?
[string "@ArkInventory\ArkInventory-30937.lua"]:12469: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "...ns\ArkInventory\ArkInventoryCollectionReputation.lua:201: attempt to index local 'object' (a nil value)"`

**Comment by arkayenro** [comment]
could you go into the config and go to advanced > threads and untick enabled (it will reset on reload)

then mouse over the reputation object again.  it should give a better error path

**Comment by Gwalkmaur** [comment]
```
1x ...ns\ArkInventory\ArkInventoryCollectionReputation.lua:201: attempt to index local 'object' (a nil value)
[string "@ArkInventory\ArkInventoryCollectionReputation.lua"]:201: in function `LevelText'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2070: in function `TooltipObjectCountGet'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2380: in function <ArkInventory\ArkInventoryTooltip.lua:2372>
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2396: in function <ArkInventory\ArkInventoryTooltip.lua:2389>
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2420: in function <ArkInventory\ArkInventoryTooltip.lua:2410>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0-4.lua"]:73: in function <...Inventory\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71>
[string "@ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0-4.lua"]:87: in function `func'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>
```

**Comment by arkayenro** [comment]
thanks, i thought it might be that.  will be fixed in the next release

**Comment by arkayenro** [comment]
fixed in 3.09.39

**Comment by Gwalkmaur** [comment]
It is still happening, however I can't even get into the Config now to get a better error path
```
2x ...aceArkInventoryConfig\ArkInventoryConfig-30936.lua:9436: attempt to call a nil value
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:9436: in function `ConfigInternalLDBMountsUpdate'
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:9423: in function `?'
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:3390: in function `ConfigInternal'
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:88: in function `ConfigRefresh'
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:94: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@ArkInventoryConfig\ArkInventoryConfig-30936.lua"]:9496: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory\ArkInventory-30939.lua"]:11609: in function `LoadAddOn'
[string "@ArkInventory\ArkInventoryConfig-30936.lua"]:19: in function `Frame_Config_Show'
[string "@ArkInventory\ArkInventoryMenu.lua"]:110: in function `func'
[string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop-30109.lua"]:731: in function <...eArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:670>
```

**Comment by arkayenro** [comment]
try the latest alpha, see if that helps

**Comment by Gwalkmaur** [comment]
I'm able to get into the config, and now I can show you the updated error message:

```
1x ArkInventory\ArkInventoryTooltip.lua:2185: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2185: in function `TooltipObjectCountGet'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2494: in function <ArkInventory\ArkInventoryTooltip.lua:2486>
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2510: in function <ArkInventory\ArkInventoryTooltip.lua:2503>
[string "@ArkInventory\ArkInventoryTooltip.lua"]:2534: in function <ArkInventory\ArkInventoryTooltip.lua:2524>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0-4.lua"]:73: in function <...Inventory\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71>
[string "@ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0-4.lua"]:87: in function `func'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>
```

**Comment by arkayenro** [comment]
i've rewritten that chunk of code to make it work with tradeskills, will have to wait for the next alpha to see if the reputation issue is still there.

could you check if you have the reputation location monitored?

**Comment by Gwalkmaur** [comment]
Turning it on looks to have stopped it.

**Comment by arkayenro** [comment]
ok cool, thats catered for in the current code so will be in the next/alpha release if you want to turn it off again

**Comment by arkayenro** [comment]
fixed in 3.09.41
