### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1493]
**What version number you are using?**
3.09.55

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail / Live

**What language is the game client set to?**
English

**Describe the bug**
There are several bugs
- Bags seem to be disappeared
- Items are not showing within battleground
- Items are disappearing such as Mythic Keystone
- Mythic Keystone has a W(wow icon) instead of the original one

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Simply use the latest version, for some of the bugs, join a bg or mythic key.

**Screenshots**
Disappearing bags:
![image](https://user-images.githubusercontent.com/57992981/129419132-6aea667f-76db-478d-b15a-8da5a4865021.png)
Disappearing item: (keystone should be there)
![image](https://user-images.githubusercontent.com/57992981/129419178-b920fcbc-219d-4a81-a250-21597ade2cc5.png)

**Additional context**
I didnt do picture of the in-battleground bug but its just simple, 0 items are shown.
THOSE BUGS ARE ONLY SINCE THIS LAST VERSION (released on curseforge 18 hours ago)
/reload fixes most of the issues except the mythic keystone icon
![image](https://user-images.githubusercontent.com/57992981/129419373-796ef075-f209-457e-96ba-071af9416c60.png)
(I dont know if reload fixes the battleground bug)

**Comment by ImUnicke** [comment]
I think this is related... same version **3.9.55**
![image](https://user-images.githubusercontent.com/4297742/129432612-9d9224b1-6b57-4be9-8621-c2457acdc794.png)
New items in the bag show the 'New item highlight' but do not actually render themselves.
One is a Trinket one is an Anima Item.

**Comment by arkayenro** [comment]
could you try [r1145-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/3425036) and let me know if its fixed or not

**Comment by awedy01** [comment]
Yeah i tried and so far i didnt notice anything wrong, i gotta confirm it within 1-2 hours.

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129448720-ce1c86d0-65fe-44a7-8283-48e22e64c902.png)
Keystone icon is still wrong

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129451224-5e97ec07-b1ad-47b7-970d-09e541a10a8d.png)
Bags disappear even without BG
I would assume its coming after teleport/ah use cuz those i did.

**Comment by awedy01** [comment]
After i entered runecarver/created my new legendary
80% of my items disappeared
![image](https://user-images.githubusercontent.com/57992981/129451292-8d145843-3f13-46f8-b034-f56b9b6a5ab0.png)

**Comment by arkayenro** [comment]
items with no data screw it up badly but reload should fix most of that as a workaround

could you try alpha 3 / [r1146-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/3425220) and let me know if its fixed or not

**Comment by MrUzagi** [comment]
I just bought the Ruffles pet from the Kyrian Renown Quartermaster. The item did not show up in my bags until a reload. After I learned the pet, the item stayed in my inventory (unusable) until a reload.

I have similar experiences with gray items as well. Hidden until a reload and remaining after selling. Not all gray items though, only some.

**Comment by MrUzagi** [comment]
I noticed searching seems a bit wonky as well. I'm not sure if this is related, but like the other stuff it started after updating to the current version.

Opening the search window drops the fps to 30 (from 60) and the initial search can lower it further to single digit fps. It used to only take some time, now it lags. The fps goes back up after a while. Closing and opening the search window drops the fps for a short while again, a couple of seconds instead of a couple of minutes.

The search window also now contains a lot of empty lines. Hovering over them shows "Unknown Object" on most of them.
![image](https://user-images.githubusercontent.com/21023158/129455815-9328b8e5-5b71-4721-9ad1-5901735c9bcd.png)

I'm not getting any LUA errors at all. Always something. :-)

**Comment by awedy01** [comment]
I logged in and have this in my chat already, not sure if it tells u anything but so u know.
----------------------------------------
[20:45] ArkInventory: v30955.3 (Alpha) [Shadowlands] Enabled 
[20:45] ArkInventory: debug: object not ready item:186625::::::::60:102::28:5:6652:7575:7695:1492:6646:1:28:2125::::: 
[20:45] ArkInventory: debug: adding to queue item:186625:0:0:0:0:0:0:0:0:0:0:0:5:6652:7575:7695:1492:6646:1:28:2125:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:180115::::::::60:102::33:6:7359:6652:7574:7617:1550:6646:1:28:1279::::: 
[20:45] ArkInventory: debug: adding to queue item:180115:0:0:0:0:0:0:0:0:0:0:0:6:7359:6652:7574:7617:1550:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:185802::::::::60:102::23:5:7731:7359:6652:1543:6646:1:28:2042::::: 
[20:45] ArkInventory: debug: adding to queue item:185802:0:0:0:0:0:0:0:0:0:0:0:5:7731:7359:6652:1543:6646:1:28:2042:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:185843:6208:::::::60:102::23:5:7731:7359:6652:1543:6646:1:28:2042::::: 
[20:45] ArkInventory: debug: adding to queue item:185843:6208:0:0:0:0:0:0:0:0:0:0:5:7731:7359:6652:1543:6646:1:28:2042:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:186756:6230:::::::60:102::74:4:6652:7695:1492:6646:1:28:2060::::: 
[20:45] ArkInventory: debug: adding to queue item:186756:6230:0:0:0:0:0:0:0:0:0:0:4:6652:7695:1492:6646:1:28:2060:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:10056::::::::60:102::::::::Player-1329-070DBAF2: 
[20:45] ArkInventory: debug: adding to queue item:10056:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:Player-1329-070DBAF2:0 
[20:45] ArkInventory: debug: object not ready item:89401::::::::60:102::14::1:28:59::::: 
[20:45] ArkInventory: debug: adding to queue item:89401:0:0:0:0:0:0:0:0:0:0:0:0:1:28:59:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:178702:6219:::::::60:102::35:6:7618:7359:6652:7574:1553:6646:::::: 
[20:45] ArkInventory: debug: adding to queue item:178702:6219:0:0:0:0:0:0:0:0:0:0:6:7618:7359:6652:7574:1553:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:186361:6205:::::::60:102::81:3:6652:1479:6646:1:28:2043::::: 
[20:45] ArkInventory: debug: adding to queue item:186361:6205:0:0:0:0:0:0:0:0:0:0:3:6652:1479:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:187380::::::::60:102::28:5:42:7575:7695:1492:6646:1:28:2043::::: 
[20:45] ArkInventory: debug: adding to queue item:187380:0:0:0:0:0:0:0:0:0:0:0:5:42:7575:7695:1492:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:186331::::::::60:102::3:4:7189:6652:1472:6646:1:28:2104::::: 
[20:45] ArkInventory: debug: adding to queue item:186331:0:0:0:0:0:0:0:0:0:0:0:4:7189:6652:1472:6646:1:28:2104:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:186734:6211:::::::60:102::27:4:6652:7695:1492:6646:1:28:2043::::: 
[20:45] ArkInventory: debug: adding to queue item:186734:6211:0:0:0:0:0:0:0:0:0:0:4:6652:7695:1492:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:178869:6168:::::::60:102::35:6:7619:7359:6652:7574:1556:6646:::::: 
[20:45] ArkInventory: debug: adding to queue item:178869:6168:0:0:0:0:0:0:0:0:0:0:6:7619:7359:6652:7574:1556:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:178926::173128::::::60:102::66:6:7088:6758:6649:6648:1532:6935:1:28:2142::::Player-1329-09A5A6FC: 
[20:45] ArkInventory: debug: adding to queue item:178926:0:173128:0:0:0:0:0:0:0:0:0:6:7088:6758:6649:6648:1532:6935:1:28:2142:0:0:0:Player-1329-09A5A6FC:0 
[20:45] ArkInventory: debug: object not ready item:179350::::::::60:102::33:5:7359:6652:7603:1550:6646:1:28:1279::::: 
[20:45] ArkInventory: debug: adding to queue item:179350:0:0:0:0:0:0:0:0:0:0:0:5:7359:6652:7603:1550:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:185278::::::::60:102::8:4:7311:6652:1492:6646:::::: 
[20:45] ArkInventory: debug: adding to queue item:185278:0:0:0:0:0:0:0:0:0:0:0:4:7311:6652:1492:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready item:178714:6229:::::::60:102::16:5:7359:6652:7644:1547:6646:1:28:1279::::: 
[20:45] ArkInventory: debug: adding to queue item:178714:6229:0:0:0:0:0:0:0:0:0:0:5:7359:6652:7644:1547:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: object queue size 17 
[20:45] ArkInventory: debug: get data for item:186734:6211:0:0:0:0:0:0:0:0:0:0:4:6652:7695:1492:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:186625:0:0:0:0:0:0:0:0:0:0:0:5:6652:7575:7695:1492:6646:1:28:2125:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:89401:0:0:0:0:0:0:0:0:0:0:0:0:1:28:59:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:185802:0:0:0:0:0:0:0:0:0:0:0:5:7731:7359:6652:1543:6646:1:28:2042:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:178869:6168:0:0:0:0:0:0:0:0:0:0:6:7619:7359:6652:7574:1556:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:178702:6219:0:0:0:0:0:0:0:0:0:0:6:7618:7359:6652:7574:1553:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:185278:0:0:0:0:0:0:0:0:0:0:0:4:7311:6652:1492:6646:0:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:186756:6230:0:0:0:0:0:0:0:0:0:0:4:6652:7695:1492:6646:1:28:2060:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:187380:0:0:0:0:0:0:0:0:0:0:0:5:42:7575:7695:1492:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:185843:6208:0:0:0:0:0:0:0:0:0:0:5:7731:7359:6652:1543:6646:1:28:2042:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:178714:6229:0:0:0:0:0:0:0:0:0:0:5:7359:6652:7644:1547:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: object queue size 7 
[20:45] ArkInventory: debug: get data for item:178714:6229:0:0:0:0:0:0:0:0:0:0:5:7359:6652:7644:1547:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:178926:0:173128:0:0:0:0:0:0:0:0:0:6:7088:6758:6649:6648:1532:6935:1:28:2142:0:0:0:Player-1329-09A5A6FC:0 
[20:45] ArkInventory: debug: get data for item:186361:6205:0:0:0:0:0:0:0:0:0:0:3:6652:1479:6646:1:28:2043:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:180115:0:0:0:0:0:0:0:0:0:0:0:6:7359:6652:7574:7617:1550:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:179350:0:0:0:0:0:0:0:0:0:0:0:5:7359:6652:7603:1550:6646:1:28:1279:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:186331:0:0:0:0:0:0:0:0:0:0:0:4:7189:6652:1472:6646:1:28:2104:0:0:0:0:0 
[20:45] ArkInventory: debug: get data for item:10056:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:Player-1329-070DBAF2:0 
[20:45] ArkInventory: debug: object not ready keystone:180653:377:10:10:6:13:128 
[20:45] ArkInventory: debug: adding to queue keystone:180653:377:10:10:6:13:128:0:0:0:0:0:0:0:0:0:0:0:0 
[20:45] ArkInventory: debug: object queue size 1 
[20:45] ArkInventory: debug: get data for keystone:180653:377:10:10:6:13:128:0:0:0:0:0:0:0:0:0:0:0:0 
[20:45] ArkInventory: debug: object not ready keystone:180653:377:10:10:6:13:128 
[20:45] ArkInventory: debug: object queue size 0
----------------------------------------

**Comment by awedy01** [comment]
btw: Keystone icon is fixed

**Comment by awedy01** [comment]
Icon of Mythic Keystone is fixed, but it is known (in Edit Mode: right click on the item) as Unknown
![image](https://user-images.githubusercontent.com/57992981/129457406-5b6cf41d-b37e-4ea0-a051-a4c0764cae53.png)
Also the name is not showing in right click

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129457974-140e781f-35d5-40f2-8439-94d8664d4c3f.png)
After doing an EPIC bg & an arena, bags disappear, keystone disappear, debug is not showing up anymore in chat.

**Comment by arkayenro** [comment]
keystones should be fixed in [alpha 5](https://www.curseforge.com/wow/addons/ark-inventory/files/3425820)

**Comment by rherzfeld** [comment]
I can confirm that the keystone display is fixed in r1149-alpha

**Comment by awedy01** [comment]
Yeah i can confirm its categorized good & icon is displaying aswell
But rest of bugs are not yet fixed
![image](https://user-images.githubusercontent.com/57992981/129480180-21498d4c-cfc9-4eb9-a716-bda6f36cd757.png)

**Comment by arkayenro** [comment]
try [alpha 7](https://www.curseforge.com/wow/addons/ark-inventory/files/3426167)

**Comment by awedy01** [comment]
Alpha 7 has a bug which i didnt report yet, dunno if its only this version or previous aswell, but lets say its a new bug
I reported on my question too
![image](https://user-images.githubusercontent.com/57992981/129482524-79eaf802-7dcb-4d37-870e-3ace4ada77d6.png)
These potions were sold and when i buy back i cannot see them in my bag until /reload
Actually after /reload when i re-sell them, i keep seeing them in my inventory even if they are sold already.

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129489147-b32861b4-bde9-4416-a05d-8c2c6c8b0e88.png)
Still alpha 7 & after an arena match thats my bag. :/

**Comment by arkayenro** [comment]
click on switch character, mouse over the current character, select erase backpack data. see if that helps.
erase the bank as well if its doing the same thing

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129564618-939ca170-424e-4768-953e-aaeded96ea5a.png)
thats all i have, nothing comes on mouseover

**Comment by arkayenro** [comment]
thats odd, it usually means you arent saving any data for any characters.

open the config and go to general > profiles > whichever profile you are using > controls > backpack > general
make sure save is ticked
then reload

**Comment by awedy01** [comment]
Yeah thats correct but in the older version where is no "Blueprint/General" option
Having SAVE UNCHECKED does not cause inventory to "disappear"
So i dunno if its a bug still or..

**Comment by arkayenro** [comment]
they just been broken up into two tabs, thats all.  all the same options have been there since 3.0.0

not having saved ticked definitely causes the issue, i can duplicate that, so at least i know where this is coming from now

**Comment by awedy01** [comment]
It seem to be fine if backpack is being saved.
Be sure to publish this version on curse so everyone can download it as soon as possible :)

**Comment by awedy01** [comment]
I just found a bug right now
When i sell items one by one, slowly right click on each
One just stayed grey, i closed my bag, opened it, now i see the item in its color like if its not sold, but no interact like no tooltip
![image](https://user-images.githubusercontent.com/57992981/129602881-45ac4347-02be-4bf1-a001-83cb98a297c7.png)

**Comment by arkayenro** [comment]
go into your profile and make sure that backpack data is being saved

if i turn that off i can duplicate the issue.  until i can figure out why its doing that should be a workaround

**Comment by arkayenro** [comment]
should be fixed in [alpha 8](https://www.curseforge.com/wow/addons/ark-inventory/files/3428782)

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129682381-4fc50168-561f-4d85-8ef9-7848af17cedf.png)
Not sure why any item will be "not ready"
So i just report it here to u (alpha 8)

**Comment by arkayenro** [comment]
its not ready when the server doesnt give back all the data and you have to ask again.  its rare but it happens
that should have been debug output though so ill fix that

**Comment by awedy01** [comment]
Do you need it for all items i meet with this debug info? Because i had more on more of my characters

**Comment by awedy01** [comment]
> should be fixed in [alpha 8](https://www.curseforge.com/wow/addons/ark-inventory/files/3428782)

sell bug seem to be fixed, yep

**Comment by awedy01** [comment]
Meanwhile i encountered a new bug?
Please let me know if you want me to open new topic for everything i find or i keep updating you here until we close this issue?!
![image](https://user-images.githubusercontent.com/57992981/129704292-671eddb9-13fd-4436-8bae-9b08bb14ee20.png)
You can see on picture, this companion should be either sold/destroyed but none of those happen. This has no sell price so it meant to be destroyed on opening vendor right? But it just doesnt happen.
Yep i have Junk auto selling on
![image](https://user-images.githubusercontent.com/57992981/129704486-d5818187-f4c2-4586-ae00-e038060edb46.png)

**Comment by arkayenro** [comment]
i can no longer destroy items - blizzard protected that function - so any items that have no sell price you need to manually destroy

**Comment by awedy01** [comment]
When did Blizz protect it? About a week ago i was destroying items via Vendor addon i linked above. Which means you can actually destroy items.

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/129720954-2aea6e28-df51-4329-b630-6fd764ae6f2f.png)
![image](https://user-images.githubusercontent.com/57992981/129720976-d5663084-ea30-40e0-8187-d0916da50399.png)
![image](https://user-images.githubusercontent.com/57992981/129720997-482ebec5-88d6-431e-bcf0-e3bd27dbd2c4.png)

Yep, it definitely allow to destroy.

**Comment by arkayenro** [comment]
thats the vendor addon destroying things, they probalby have something to click on to kick it off?  you cant auto destroy things any more.

**Comment by awedy01** [comment]
No you dont need to click. There is a keybind since a year or even more. You set it to whatever you want, like O, and if u press O it will destroy all the items which should be destroyed depends on rule.

**Comment by awedy01** [comment]
[13:14] A Call to Ardenweald completed. 
[13:14] You receive item: [Bounty of the Grove Wardens] 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 15, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 7, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 2, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 4, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 8, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 16, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 5, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 10, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 9, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 3, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 12, true ) 
[13:15] ArkInventory: EraseSavedData( Awely - Ravencrest, 14, true )


Latest Alpha version, this debug msgs happen a lot, i dont rly know when, it happens at mailbox close, happened after teleportation to oribos, happens a lot of times.

**Comment by arkayenro** [comment]
check [alpha 10](https://www.curseforge.com/wow/addons/ark-inventory/files/3430371), that should fix the last of the issues, and stop the debug output

**Comment by awedy01** [comment]
What are actually the last of the issues? What should i look for?

**Comment by awedy01** [comment]
It is working perfectly so far!! Wont close the issue yet and i will update here if there will be anything i notice today/tomorrow.

**Comment by awedy01** [comment]
Everything is ok so far. I hope to see this version downloadable on curse NOT as alpha cuz right now its sharing the very old buggy version which damages the reputation of this awesome addon.
