### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lossolsun** [arkayenro/arkinventory#1575]
**What version number you are using?**
3.09.67 [Shadowlands] and the immediately previous version

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**

Toybox is having the source and expansion filters unchecked upon opening. I found Issue #845 with the similar thing happening. I have confirmed that this happens with only ArkInventory enabled.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Open the toybox, check all sources and expansions. Close toybox. Wait about 5 seconds, and open the toybox again. The sources and expansions will be unchecked.

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
should be fixed in the next release

**Comment by gruubar** [comment]
This bug is either still occurring or reoccurring in 3.10.03 in 10.0. Arkinventory only addon. Toybox filters still getting broken, even with all toybox settings disabled in Arkinventory. Thanks for looking into this.

**Comment by KHSebastian** [comment]
Can confirm, this issue is still happening for me as well, on 3.10.09, with only Arkinventory enabled. If there's any info I can provide to help, I can.

**Comment by arkayenro** [comment]
i thought i had fixed those a while back.  ill take another look when i get a chance

**Comment by arkayenro** [comment]
should be fixed next release.  they got inverted at some point so it would flip the values when it restored them

**Comment by arkayenro** [comment]
fixed, hopefully, in 3.10.09 alpha 3
