### ISSUE TITLE
[BUG] Rules - not applied during addon initialization

### ISSUE THREAD

**Issue by Horogg** [arkayenro/arkinventory#1711]
**What version number you are using?**
3.10.09

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
EN

**Describe the bug**
Version 3.10.09 and higher have problems with initialization of ArkInventory. After login or reload UI, rules are not aplicated to items and Refresh button not helping. Helps only when I open Rules window, go to edit specific rule and click on Accept button. After that Backpack apply rules on items and update UI. When I "re-save" one rule, all rules applied after Backpack update UI.

This is example of problematic rule(s), but I don't know if this is inside this rule or in another place (e.g. most of items which I filtering are inside new Reagent bag).

`not q(0) and (type("tradeskill") or tooltip("crafting reagent"))`
`not q(0) and (type("tradeskill") or tooltip("crafting reagent")) and expansion()`

**Result of my investigation:**
Issue is in this part of rule `not q(0)`. After remove this part, initialization od ArkInventory works again.
_(tested on 3.10.09, because 3.10.10 have many issues with addon initialization)_

**Comment by arkayenro** [comment]
youre going to have to explain the initialization issues first because theyre probably related, or at least need to be fixed anyway.

**Comment by Neischa** [comment]
I have similar issue, some of my items are in default bag instead of assigned bag, couple of equipment parts, when I reload UI (sometimes I have to do it multiple times) it gets fixed for some time... no error message and I think it is related to how quickly I open bagpack after a reload... if I give it some time - 5 seconds at least, it works fine, but if less, then some items are not caught by a rule, like if there is a loop running through all items in inventory is interrupted by bag opening action. This also happens during regular gameplay, sometimes some items rule assignment is lost, I couldnt figure out why or when...

**Comment by arkayenro** [comment]
try 3.10.10 alpha 1

**Comment by Neischa** [comment]
Still happens after reload...

**Comment by arkayenro** [comment]
try disabling the pre-load for the bag/bank

**Comment by arkayenro** [comment]
try 3.10.10 alpha 2

**Comment by arkayenro** [comment]
try 3.10.10 alpha 4.  pretty sure its fixed in there.  the quality was being saved wrong

**Comment by Neischa** [comment]
seems to be working, great, thanks!:)

**Comment by Neischa** [comment]
I just downloaded new stable version and the bug is there again... Didnt you forgot to add it there?

**Comment by arkayenro** [comment]
no, i added it in there, i just removed the saved data and missed the rule code so it was still looking at the saved data

try 3.10.11 alpha 1

**Comment by Neischa** [comment]
It seems to work again, thanks!:)
