### ISSUE TITLE
[BUG] LUA error & printout - Map.Location

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1910]
**What version number you are using?**
3.10.33-alpha-7

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Version alpha-7 started spamming me with the errors below:

[23:01:20] ArkInventory: ERROR> Map.Location[5].StorageBags[3] is not mapped
[23:01:20] ArkInventory: ERROR> ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:13: ERROR> Map.Location[5].StorageBags[3] is not mapped
[23:01:28] ArkInventory: ERROR> Map.Location[5].StorageBags[3] is not mapped
[23:01:28] ArkInventory: ERROR> ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:13: ERROR> Map.Location[5].StorageBags[3] is not mapped

LUA errors:
22x ArkInventory/Core/ArkInventoryUtil.lua:13: ERROR> Map.Location[2] is not mapped
[string "=[C]"]: in function `error'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:13: in function `Error'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:18: in function `Assert'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:173: in function `MapGetWindowBags'
[string "@ArkInventory/Core/ArkInventoryAPI.lua"]:190: in function `(for generator)'
[string "@CanIMogIt/Plugins/arkinventory.lua"]:167: in main chunk

Locals:
(*temporary) = "|cffff2020ERROR> Map.Location[2] is not mapped"

**To Reproduce**
Open mails (with Open All).

**Screenshots**
N/A

**Additional context**
This issue was not present in alpha-5.

**Comment by arkayenro** [comment]
you may need to disable canimogit for the moment, or see if theres a way to disable arkinventory support in it.  the changes i've made to my code may have broken it but there is an issue i need to fix in that api call.

**Comment by hollo6** [comment]
Thanks for the update! I just rolled back to alpha-5 for now.

**Comment by hollo6** [comment]
I'm still getting this error in alpha-8, but I just realized that these versions are only for TWW? Are they really not supposed to work with Retail?

**Comment by arkayenro** [comment]
they should work in retail but with the number of changes im making to get it to work in war within its probably going to break a a lot of stuff along the way so its mostly as a heads up that theres probably going to be issues.

is it the exact same error youre getting?

**Comment by arkayenro** [comment]
nvm, figured it out, it was the action (mail in this case) code that i hadnt updated yet.  should be fixed in the next alpha

**Comment by arkayenro** [comment]
the canimogit issue should also be resolve in teh next alpha

**Comment by hollo6** [comment]
Sadly it's still happening. I get this when opening mails:
[17:08:41] ArkInventory: ERROR> Map.Storage[5].Bag[3] is not mapped
[17:08:41] ArkInventory: ERROR> ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:13: ERROR> Map.Storage[5].Bag[3] is not mapped

But no actual LUA error this time.

**Comment by arkayenro** [comment]
mail issue should be fixed in alpha 12 (tomorrow)

**Comment by hollo6** [comment]
Indeed it's OK now, thanks!
