### ISSUE TITLE
Error when logging in to beta with only AI

### ISSUE THREAD

**Issue by gunner007cd** [arkayenro/arkinventory#759]
When logging into BETA/PTR realms with only ArkInventory enabled, get the following error. 

Message: ...ce\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua:2243: bad argument #2 to 'format' (string expected, got nil)
Time: 07/17/16 08:28:32
Count: 1
Stack: [C]: in function `format'
...ce\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua:2243: in function `initFunction'
Interface\FrameXML\UIDropDownMenu.lua:69: in function `UIDropDownMenu_Initialize'
...ce\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua:2214: in function <...ce\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua:2213>

Locals: (*temporary) = "(%s)"
(*temporary) = nil
(*temporary) = "string expected, got nil"

Goes away once AI is disabled.

**Comment by arkayenro** [comment]
i didnt even check to see if that was because of AI, i just presumed it was a normal error

seems like the wardrobe doesnt like being loaded too eary

fixed in 3.06.05

**Comment by gunner007cd** [comment]
Seems the error is still present in 3.06.05 - though maybe unrelated, the addon no longer loads at all. No additional error messages. Did the Blizzard add-ons disappear in Legion? I noticed they're no longer created.
