### ISSUE TITLE
Errors and poor performance since today's update

### ISSUE THREAD

**Issue by sparrowlab** [arkayenro/arkinventory#962]
Since today's update, I'm getting extremely poor performance in WoW — low FPS, periods of lag in combat. Additionally, I'm getting this lua error:

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:10222: script ran too long
Time: Wed Aug  2 19:27:25 2017
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:10222: script ran too longInterface\SharedXML\SharedBasicControls.lua:204: in function `origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: in function `resume'
Interface\AddOns\ArkInventory\ArkInventory.lua:10222: in function `ThreadResume'
[string "*:OnUpdate"]:4: in function <[string "*:OnUpdate"]:1>

Locals: errorMessage = "Interface\AddOns\ArkInventory\ArkInventory.lua:10222: script ran too long"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by arkayenro** [comment]
timing out at line 10222 should be impossible as the code has only just come back to run from a previous yield, it can only have been running for a few ms at best, no where near the 200ms limit

in the config > workarounds enable the thread debug, that should show you when ai is updating so you can tell if the laggy bits happen at the same time as any debug output

**Comment by fivecatsrc** [comment]
Hi, I'm having the same issue. I enabled the thread debug and that does appear to be when the lag is happening. Do you have any suggestions for a fix from my end?
![wowscrnshot_080317_231652](https://user-images.githubusercontent.com/29333883/28955196-e9f68d70-78a1-11e7-9eb2-a904c1669b11.jpg)

**Comment by arkayenro** [comment]
fivecatsrc - turn off instant sorting, that should stop it for the moment (i presume its happening after you loot/use something)

**Comment by fivecatsrc** [comment]
Actually it's mostly happening as I enter/exit combat, but I'll give that a try. Thanks!

**Comment by arkayenro** [comment]
i've updated the code to not refresh windows unless theyre visible, or need initilising so that should fix it

theres an option to refresh when leaving combat so thats probably causing it but we dont need to do it if theyre not visible

ill upload an alpha soon

**Comment by fivecatsrc** [comment]
Thanks! I really appreciate it.

**Comment by fivecatsrc** [comment]
Oops it's me again. I've updated to the alpha you put up, and have the Manual sorting on, but the stuttering when enter/exit combat is still an issue. For now I've just disabled the addon (which breaks my little sort-needy heart).

![wowscrnshot_080417_074201](https://user-images.githubusercontent.com/29333883/28971824-bc7e451a-78ea-11e7-8be5-ba6f2100caeb.jpg)
![wowscrnshot_080417_074140](https://user-images.githubusercontent.com/29333883/28971823-bc7d202c-78ea-11e7-84ea-0c1c77265e72.jpg)
![wowscrnshot_080417_074039](https://user-images.githubusercontent.com/29333883/28971825-bc818bf8-78ea-11e7-93d5-f0ae2aaf0f4d.jpg)

**Comment by arkayenro** [comment]
whats weird is that you arent getting the debug message for non visible windows after the initial load and because the window isnt visible.  are you using the 667 alpha?

eg, once the game has loaded and all the debug messages stop, leaving the bag window closed, if you go and kill something and loot it you should see a debug message like THREAD> p4-draw-1 aborting, not init, not visible

that means it wanted to update the window but didnt continue because it wasnt visible

when you enter combat ai doesnt care, it just sets a variable so it knows youve entered it, it doesnt try to refresh all the windows at that time

leaving combat it can try to update all the windows if youve disabled cooldowns in combat

**Comment by fivecatsrc** [comment]
Yeah, I had downloaded & installed the 667 alpha at the time of those screenshots, and it was long after I'd let the initial debug go through from logging in. I'll give it another try, maybe I thought I installed it but didn't click 'OK to overwrite files' or something.

**Comment by fivecatsrc** [comment]
Yup, as suspected, I fucked up on something lol. I reinstalled the 667 alpha just now and am getting the right error. Sorry to have wasted your time on my mistake :s
![wowscrnshot_080517_120341](https://user-images.githubusercontent.com/29333883/28997628-6ad1b6d8-79d6-11e7-822e-66adfb47e073.jpg)

**Comment by arkayenro** [comment]
ok, so if you re-enable instant sorting, and disable the debug, is it still laggy entering/exiting combat or looting?

do you get any errors, or just the lag?

**Comment by fivecatsrc** [comment]
Re-enabled instant sorting - there's like a half-second pause when looting, but other than that no lag at all now.
